# Generated by Django 3.1.7 on 2021-03-22 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cableoperators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitinetwork',
            name='phone',
            field=models.BigIntegerField(null=True),
        ),
    ]
