# Generated by Django 3.1.7 on 2021-03-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cableoperators', '0002_sitinetwork_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitinetwork',
            name='percentage',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
