# Generated by Django 3.1.7 on 2021-03-23 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cableoperators', '0003_sitinetwork_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitinetwork',
            name='percentage',
            field=models.IntegerField(null=True),
        ),
    ]
