# Generated by Django 3.1.7 on 2021-03-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cableoperators', '0004_auto_20210323_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitinetwork',
            name='dob',
            field=models.DateField(max_length=15, null=True),
        ),
    ]
